from pathlib import Path

APP_DIR = Path(__file__).resolve().parent
MODEL_PATH = APP_DIR / "landslide_rfc_model.pkl"
INPUT_COLUMNS = ["Geology_Type", "Land_Use", "Slope_Angle", "Rainfall_3Day", "Effective_Rainfall_mm", "Soil_Saturation", "Vegetation_Cover", "Elevation_m", "Soil_Erosion_Rate", "Pore_Pressure_Ratio", "Seismic_PGA_g"]
CATEGORICAL_OPTIONS = {"Geology_Type": ["Colluvium", "Igneous_Metamorphic", "Residual_Soil", "Sedimentary_Rock", "Weathered_Rock"], "Land_Use": ["Agriculture", "Barren", "Forest", "Urban"]}

NUMERIC_INPUTS = {
    "Slope_Angle": (0.0, 90.0, 30.0, 1.0, "°", "%.0f"), "Rainfall_3Day": (0.0, 500.0, 100.0, 5.0, "mm", "%.0f"), "Effective_Rainfall_mm": (0.0, 500.0, 80.0, 5.0, "mm", "%.0f"),
    "Soil_Saturation": (0.0, 1.0, 0.5, 0.01, "", "%.2f"), "Vegetation_Cover": (0.0, 1.0, 0.5, 0.01, "", "%.2f"), "Elevation_m": (0.0, 5000.0, 500.0, 10.0, "m", "%.0f"),
    "Soil_Erosion_Rate": (0.0, 20.0, 1.0, 0.1, "", "%.1f"), "Pore_Pressure_Ratio": (0.0, 1.0, 0.5, 0.01, "", "%.2f"), "Seismic_PGA_g": (0.0, 1.0, 0.1, 0.01, "g", "%.2f"),
}

MONITORING_STATIONS = {
    "Kedarnath, UT": {"lat": 30.7346, "lon": 79.0669, "risk": "Extreme", "base": {"Slope_Angle": 65, "Rainfall_3Day": 490, "Soil_Saturation": 0.99, "Pore_Pressure_Ratio": 0.96, "Seismic_PGA_g": 0.45, "Effective_Rainfall_mm": 450, "Elevation_m": 3583, "Soil_Erosion_Rate": 15, "Vegetation_Cover": 0.1, "Geology_Type": "Weathered_Rock", "Land_Use": "Barren"}},
    "Wayanad, KL": {"lat": 11.6854, "lon": 76.1320, "risk": "Extreme", "base": {"Slope_Angle": 52, "Rainfall_3Day": 540, "Soil_Saturation": 0.98, "Pore_Pressure_Ratio": 0.94, "Seismic_PGA_g": 0.15, "Effective_Rainfall_mm": 510, "Elevation_m": 700, "Soil_Erosion_Rate": 12, "Vegetation_Cover": 0.6, "Geology_Type": "Colluvium", "Land_Use": "Agriculture"}},
    "Darjeeling, WB": {"lat": 27.0360, "lon": 88.2627, "risk": "Extreme", "base": {"Slope_Angle": 58, "Rainfall_3Day": 475, "Soil_Saturation": 0.97, "Pore_Pressure_Ratio": 0.95, "Seismic_PGA_g": 0.38, "Effective_Rainfall_mm": 440, "Elevation_m": 2045, "Soil_Erosion_Rate": 14, "Vegetation_Cover": 0.4, "Geology_Type": "Residual_Soil", "Land_Use": "Forest"}},
    "Shimla, HP": {"lat": 31.1048, "lon": 77.1734, "risk": "High", "base": {"Slope_Angle": 42, "Rainfall_3Day": 280, "Soil_Saturation": 0.75, "Pore_Pressure_Ratio": 0.65, "Seismic_PGA_g": 0.25, "Effective_Rainfall_mm": 250, "Elevation_m": 2276, "Soil_Erosion_Rate": 8, "Vegetation_Cover": 0.5, "Geology_Type": "Weathered_Rock", "Land_Use": "Urban"}},
    "Munnar, KL": {"lat": 10.0889, "lon": 77.0595, "risk": "High", "base": {"Slope_Angle": 35, "Rainfall_3Day": 310, "Soil_Saturation": 0.82, "Pore_Pressure_Ratio": 0.55, "Seismic_PGA_g": 0.12, "Effective_Rainfall_mm": 290, "Elevation_m": 1532, "Soil_Erosion_Rate": 9, "Vegetation_Cover": 0.7, "Geology_Type": "Colluvium", "Land_Use": "Agriculture"}},
    "Guwahati, AS": {"lat": 26.1445, "lon": 91.7362, "risk": "High", "base": {"Slope_Angle": 28, "Rainfall_3Day": 240, "Soil_Saturation": 0.78, "Pore_Pressure_Ratio": 0.45, "Seismic_PGA_g": 0.38, "Effective_Rainfall_mm": 210, "Elevation_m": 55, "Soil_Erosion_Rate": 6, "Vegetation_Cover": 0.3, "Geology_Type": "Sedimentary_Rock", "Land_Use": "Urban"}},
    "Itanagar, AR": {"lat": 27.0844, "lon": 93.6053, "risk": "High", "base": {"Slope_Angle": 38, "Rainfall_3Day": 295, "Soil_Saturation": 0.85, "Pore_Pressure_Ratio": 0.60, "Seismic_PGA_g": 0.32, "Effective_Rainfall_mm": 270, "Elevation_m": 320, "Soil_Erosion_Rate": 10, "Vegetation_Cover": 0.8, "Geology_Type": "Weathered_Rock", "Land_Use": "Forest"}},
    "Pune, MH": {"lat": 18.5204, "lon": 73.8567, "risk": "Low", "base": {"Slope_Angle": 12, "Rainfall_3Day": 40, "Soil_Saturation": 0.30, "Pore_Pressure_Ratio": 0.20, "Seismic_PGA_g": 0.08, "Effective_Rainfall_mm": 35, "Elevation_m": 560, "Soil_Erosion_Rate": 2, "Vegetation_Cover": 0.4, "Geology_Type": "Igneous_Metamorphic", "Land_Use": "Urban"}},
    "Bangalore, KA": {"lat": 12.9716, "lon": 77.5946, "risk": "Low", "base": {"Slope_Angle": 5, "Rainfall_3Day": 10, "Soil_Saturation": 0.15, "Pore_Pressure_Ratio": 0.10, "Seismic_PGA_g": 0.02, "Effective_Rainfall_mm": 5, "Elevation_m": 920, "Soil_Erosion_Rate": 1, "Vegetation_Cover": 0.3, "Geology_Type": "Igneous_Metamorphic", "Land_Use": "Urban"}},
    "Bhopal, MP": {"lat": 23.2599, "lon": 77.4126, "risk": "Low", "base": {"Slope_Angle": 8, "Rainfall_3Day": 25, "Soil_Saturation": 0.25, "Pore_Pressure_Ratio": 0.15, "Seismic_PGA_g": 0.05, "Effective_Rainfall_mm": 20, "Elevation_m": 427, "Soil_Erosion_Rate": 2, "Vegetation_Cover": 0.4, "Geology_Type": "Sedimentary_Rock", "Land_Use": "Urban"}},
    "Hyderabad, TS": {"lat": 17.3850, "lon": 78.4867, "risk": "Low", "base": {"Slope_Angle": 10, "Rainfall_3Day": 5, "Soil_Saturation": 0.10, "Pore_Pressure_Ratio": 0.05, "Seismic_PGA_g": 0.01, "Effective_Rainfall_mm": 2, "Elevation_m": 542, "Soil_Erosion_Rate": 1, "Vegetation_Cover": 0.2, "Geology_Type": "Igneous_Metamorphic", "Land_Use": "Urban"}},
    "Jaipur, RJ": {"lat": 26.9124, "lon": 75.7873, "risk": "Low", "base": {"Slope_Angle": 15, "Rainfall_3Day": 0, "Soil_Saturation": 0.05, "Pore_Pressure_Ratio": 0.05, "Seismic_PGA_g": 0.04, "Effective_Rainfall_mm": 0, "Elevation_m": 431, "Soil_Erosion_Rate": 3, "Vegetation_Cover": 0.1, "Geology_Type": "Weathered_Rock", "Land_Use": "Barren"}},
    "Nagpur, MH": {"lat": 21.1458, "lon": 79.0882, "risk": "Low", "base": {"Slope_Angle": 4, "Rainfall_3Day": 15, "Soil_Saturation": 0.20, "Pore_Pressure_Ratio": 0.12, "Seismic_PGA_g": 0.06, "Effective_Rainfall_mm": 10, "Elevation_m": 310, "Soil_Erosion_Rate": 1, "Vegetation_Cover": 0.4, "Geology_Type": "Igneous_Metamorphic", "Land_Use": "Urban"}},
    "Ranchi, JH": {"lat": 23.3441, "lon": 85.3094, "risk": "Low", "base": {"Slope_Angle": 18, "Rainfall_3Day": 60, "Soil_Saturation": 0.40, "Pore_Pressure_Ratio": 0.25, "Seismic_PGA_g": 0.10, "Effective_Rainfall_mm": 50, "Elevation_m": 651, "Soil_Erosion_Rate": 3, "Vegetation_Cover": 0.5, "Geology_Type": "Igneous_Metamorphic", "Land_Use": "Forest"}},
    "Ahmedabad, GJ": {"lat": 23.0225, "lon": 72.5714, "risk": "Low", "base": {"Slope_Angle": 2, "Rainfall_3Day": 5, "Soil_Saturation": 0.12, "Pore_Pressure_Ratio": 0.08, "Seismic_PGA_g": 0.03, "Effective_Rainfall_mm": 2, "Elevation_m": 53, "Soil_Erosion_Rate": 1, "Vegetation_Cover": 0.2, "Geology_Type": "Sedimentary_Rock", "Land_Use": "Urban"}},
    "Gangtok, SK": {"lat": 27.3314, "lon": 88.6138, "risk": "High", "base": {"Slope_Angle": 45, "Rainfall_3Day": 340, "Soil_Saturation": 0.88, "Pore_Pressure_Ratio": 0.62, "Seismic_PGA_g": 0.35, "Effective_Rainfall_mm": 310, "Elevation_m": 1650, "Soil_Erosion_Rate": 11, "Vegetation_Cover": 0.5, "Geology_Type": "Weathered_Rock", "Land_Use": "Urban"}},
    "Kohima, NL": {"lat": 25.6751, "lon": 94.1086, "risk": "High", "base": {"Slope_Angle": 40, "Rainfall_3Day": 310, "Soil_Saturation": 0.84, "Pore_Pressure_Ratio": 0.58, "Seismic_PGA_g": 0.30, "Effective_Rainfall_mm": 280, "Elevation_m": 1444, "Soil_Erosion_Rate": 9, "Vegetation_Cover": 0.7, "Geology_Type": "Residual_Soil", "Land_Use": "Forest"}},
    "Aizawl, MZ": {"lat": 23.7307, "lon": 92.7173, "risk": "Extreme", "base": {"Slope_Angle": 62, "Rainfall_3Day": 485, "Soil_Saturation": 0.98, "Pore_Pressure_Ratio": 0.94, "Seismic_PGA_g": 0.42, "Effective_Rainfall_mm": 460, "Elevation_m": 1132, "Soil_Erosion_Rate": 14, "Vegetation_Cover": 0.2, "Geology_Type": "Colluvium", "Land_Use": "Barren"}},
}